print('This program does math.')
taha = int(input('Number 1: '))
ua = int(input('Number 2: '))
print('')
print(taha,'+',ua,"=",taha + ua)
print(taha,'-',ua,'=',taha - ua)
print(taha,'*',ua,'=',taha * ua)
print(taha,'/',ua,'=',(taha / ua,'.2f'))
print(taha,'//',ua,'=',taha // ua)
print(taha,'^',ua ,'=', taha ** ua)
