print('This program calculates the area of a triangle.')
print('')
base = int(input('Enter the base: '))
height = int(input('Enter the height: '))
area = ((base * height) / 2)
print('')
print('The area is '+ str(area))